// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rbldzsaakjifwuvekaho.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJibGR6c2Fha2ppZnd1dmVrYWhvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI2OTIzMjQsImV4cCI6MjA1ODI2ODMyNH0.UrSEQCCJNhImAEO0fF0_QUx0fIaIITcJV7k3wuhnXQ4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);